#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemManagement.DataAccess.User.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="systemManagementAPI")]
	public partial class UserDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public UserDataContext() : 
				base(global::SystemManagement.DataAccess.Properties.Settings.Default.systemManagementAPIConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UserDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UserDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UserDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UserDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spr_getUser")]
		public ISingleResult<spr_getUserResult> spr_getUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(128)")] string usr_userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usr_userName);
			return ((ISingleResult<spr_getUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spr_getUsers")]
		public ISingleResult<spr_getUsersResult> spr_getUsers()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spr_getUsersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spr_setAddBalance")]
		public int spr_setAddBalance([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usr_userNameDestiny, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> valueTransfer)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usr_userNameDestiny, valueTransfer);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spr_setUser")]
		public int spr_setUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usr_userName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usr_password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usr_fullName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string usr_documentType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string usr_numberDocument, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usr_email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string usr_role, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usr_creationUser)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usr_userName, usr_password, usr_fullName, usr_documentType, usr_numberDocument, usr_email, usr_role, usr_creationUser);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spr_updateUser")]
		public int spr_updateUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usr_userName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usr_password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usr_fullName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string usr_documentType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string usr_numberDocument, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usr_email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string usr_role, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usr_modificationUser, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string usr_status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usr_userName, usr_password, usr_fullName, usr_documentType, usr_numberDocument, usr_email, usr_role, usr_modificationUser, usr_status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spr_setDeleteBalance")]
		public ISingleResult<spr_setDeleteBalanceResult> spr_setDeleteBalance([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usr_userNameDestiny, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> valueTransfer)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usr_userNameDestiny, valueTransfer);
			return ((ISingleResult<spr_setDeleteBalanceResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spr_setTransferBalance")]
		public ISingleResult<spr_setTransferBalanceResult> spr_setTransferBalance([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usr_userNameOrigin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string usr_userNameDestiny, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,2)")] System.Nullable<decimal> valueTransfer)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usr_userNameOrigin, usr_userNameDestiny, valueTransfer);
			return ((ISingleResult<spr_setTransferBalanceResult>)(result.ReturnValue));
		}
	}
	
	public partial class spr_getUserResult
	{
		
		private decimal _usrID;
		
		private string _usr_code;
		
		private string _usr_userName;
		
		private string _usr_password;
		
		private string _usr_fullName;
		
		private string _usr_documentType;
		
		private string _usr_numberDocument;
		
		private string _usr_email;
		
		private System.Nullable<decimal> _usr_balance;
		
		private string _usr_role;
		
		private string _rl_name;
		
		private string _usr_status;
		
		public spr_getUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrID", DbType="Decimal(18,0) NOT NULL")]
		public decimal usrID
		{
			get
			{
				return this._usrID;
			}
			set
			{
				if ((this._usrID != value))
				{
					this._usrID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_code", DbType="VarChar(10)")]
		public string usr_code
		{
			get
			{
				return this._usr_code;
			}
			set
			{
				if ((this._usr_code != value))
				{
					this._usr_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_userName", DbType="VarChar(50)")]
		public string usr_userName
		{
			get
			{
				return this._usr_userName;
			}
			set
			{
				if ((this._usr_userName != value))
				{
					this._usr_userName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_password", DbType="VarChar(50)")]
		public string usr_password
		{
			get
			{
				return this._usr_password;
			}
			set
			{
				if ((this._usr_password != value))
				{
					this._usr_password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_fullName", DbType="VarChar(100)")]
		public string usr_fullName
		{
			get
			{
				return this._usr_fullName;
			}
			set
			{
				if ((this._usr_fullName != value))
				{
					this._usr_fullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_documentType", DbType="VarChar(25)")]
		public string usr_documentType
		{
			get
			{
				return this._usr_documentType;
			}
			set
			{
				if ((this._usr_documentType != value))
				{
					this._usr_documentType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_numberDocument", DbType="VarChar(10)")]
		public string usr_numberDocument
		{
			get
			{
				return this._usr_numberDocument;
			}
			set
			{
				if ((this._usr_numberDocument != value))
				{
					this._usr_numberDocument = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_email", DbType="VarChar(50)")]
		public string usr_email
		{
			get
			{
				return this._usr_email;
			}
			set
			{
				if ((this._usr_email != value))
				{
					this._usr_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_balance", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> usr_balance
		{
			get
			{
				return this._usr_balance;
			}
			set
			{
				if ((this._usr_balance != value))
				{
					this._usr_balance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_role", DbType="VarChar(10)")]
		public string usr_role
		{
			get
			{
				return this._usr_role;
			}
			set
			{
				if ((this._usr_role != value))
				{
					this._usr_role = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rl_name", DbType="VarChar(50)")]
		public string rl_name
		{
			get
			{
				return this._rl_name;
			}
			set
			{
				if ((this._rl_name != value))
				{
					this._rl_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_status", DbType="VarChar(1)")]
		public string usr_status
		{
			get
			{
				return this._usr_status;
			}
			set
			{
				if ((this._usr_status != value))
				{
					this._usr_status = value;
				}
			}
		}
	}
	
	public partial class spr_getUsersResult
	{
		
		private decimal _usrID;
		
		private string _usr_code;
		
		private string _usr_userName;
		
		private string _usr_fullName;
		
		private string _usr_documentType;
		
		private string _usr_numberDocument;
		
		private string _usr_password;
		
		private string _usr_email;
		
		private System.Nullable<decimal> _usr_balance;
		
		private string _usr_role;
		
		private string _rl_name;
		
		private string _usr_status;
		
		public spr_getUsersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrID", DbType="Decimal(18,0) NOT NULL")]
		public decimal usrID
		{
			get
			{
				return this._usrID;
			}
			set
			{
				if ((this._usrID != value))
				{
					this._usrID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_code", DbType="VarChar(10)")]
		public string usr_code
		{
			get
			{
				return this._usr_code;
			}
			set
			{
				if ((this._usr_code != value))
				{
					this._usr_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_userName", DbType="VarChar(50)")]
		public string usr_userName
		{
			get
			{
				return this._usr_userName;
			}
			set
			{
				if ((this._usr_userName != value))
				{
					this._usr_userName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_fullName", DbType="VarChar(100)")]
		public string usr_fullName
		{
			get
			{
				return this._usr_fullName;
			}
			set
			{
				if ((this._usr_fullName != value))
				{
					this._usr_fullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_documentType", DbType="VarChar(25)")]
		public string usr_documentType
		{
			get
			{
				return this._usr_documentType;
			}
			set
			{
				if ((this._usr_documentType != value))
				{
					this._usr_documentType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_numberDocument", DbType="VarChar(10)")]
		public string usr_numberDocument
		{
			get
			{
				return this._usr_numberDocument;
			}
			set
			{
				if ((this._usr_numberDocument != value))
				{
					this._usr_numberDocument = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_password", DbType="VarChar(50)")]
		public string usr_password
		{
			get
			{
				return this._usr_password;
			}
			set
			{
				if ((this._usr_password != value))
				{
					this._usr_password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_email", DbType="VarChar(50)")]
		public string usr_email
		{
			get
			{
				return this._usr_email;
			}
			set
			{
				if ((this._usr_email != value))
				{
					this._usr_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_balance", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> usr_balance
		{
			get
			{
				return this._usr_balance;
			}
			set
			{
				if ((this._usr_balance != value))
				{
					this._usr_balance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_role", DbType="VarChar(10)")]
		public string usr_role
		{
			get
			{
				return this._usr_role;
			}
			set
			{
				if ((this._usr_role != value))
				{
					this._usr_role = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rl_name", DbType="VarChar(50)")]
		public string rl_name
		{
			get
			{
				return this._rl_name;
			}
			set
			{
				if ((this._rl_name != value))
				{
					this._rl_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_status", DbType="VarChar(1)")]
		public string usr_status
		{
			get
			{
				return this._usr_status;
			}
			set
			{
				if ((this._usr_status != value))
				{
					this._usr_status = value;
				}
			}
		}
	}
	
	public partial class spr_setDeleteBalanceResult
	{
		
		private System.Nullable<int> _result;
		
		public spr_setDeleteBalanceResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result", DbType="Int")]
		public System.Nullable<int> result
		{
			get
			{
				return this._result;
			}
			set
			{
				if ((this._result != value))
				{
					this._result = value;
				}
			}
		}
	}
	
	public partial class spr_setTransferBalanceResult
	{
		
		private System.Nullable<int> _result;
		
		public spr_setTransferBalanceResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result", DbType="Int")]
		public System.Nullable<int> result
		{
			get
			{
				return this._result;
			}
			set
			{
				if ((this._result != value))
				{
					this._result = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
