#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemManagement.DataAccess.Authentication.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="systemManagementAPI")]
	public partial class AuthenticationDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public AuthenticationDataContext() : 
				base(global::SystemManagement.DataAccess.Properties.Settings.Default.systemManagementAPIConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AuthenticationDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AuthenticationDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AuthenticationDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AuthenticationDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spr_closeSession")]
		public int spr_closeSession([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sesID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sesID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spr_createSession")]
		public int spr_createSession([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sesID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> usrID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sesID, usrID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spr_validateSession")]
		public ISingleResult<spr_validateSessionResult> spr_validateSession([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sesID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> usrID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sesID, usrID);
			return ((ISingleResult<spr_validateSessionResult>)(result.ReturnValue));
		}
	}
	
	public partial class spr_validateSessionResult
	{
		
		private string _sesID;
		
		private decimal _usrID;
		
		private string _ses_status;
		
		private System.DateTime _ses_date;
		
		public spr_validateSessionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sesID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sesID
		{
			get
			{
				return this._sesID;
			}
			set
			{
				if ((this._sesID != value))
				{
					this._sesID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrID", DbType="Decimal(18,0) NOT NULL")]
		public decimal usrID
		{
			get
			{
				return this._usrID;
			}
			set
			{
				if ((this._usrID != value))
				{
					this._usrID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ses_status", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ses_status
		{
			get
			{
				return this._ses_status;
			}
			set
			{
				if ((this._ses_status != value))
				{
					this._ses_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ses_date", DbType="DateTime NOT NULL")]
		public System.DateTime ses_date
		{
			get
			{
				return this._ses_date;
			}
			set
			{
				if ((this._ses_date != value))
				{
					this._ses_date = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
